### ISSUE TITLE
actions are broke

### ISSUE THREAD

**Issue by nebulazorua** [riconuts/FNF-Troll-Engine#48]
### IDK TYPE HERE!!!

actions are broke idk how to do workflow shit so if someone wants to fix them it'd be appreciate

**Comment by nebulazorua** [comment]
got windows working just need mac and linux working

**Comment by riconuts** [comment]
next time these actions get used they'll probably be broken again lolz

**Comment by nebulazorua** [comment]
> by the next time these actions get used they'll probably be broken again lolz

they dont even work LOL idek why its just lime being autistic

**Comment by nebulazorua** [comment]
just gonna leave this for rn
hopefully someone else sees this and knows wtf is going wrong !

**Comment by swordcube** [comment]
just steal the actions from codename :troll:

**Comment by swordcube** [comment]
> > just steal the actions from codename 🧌
> 
> I FUCKING MIGHT

lmao

**Comment by nebulazorua** [comment]
> > > just steal the actions from codename 🧌
> > 
> > 
> > I FUCKING MIGHT
> 
> lmao

![image](https://github.com/user-attachments/assets/68a24b2d-dc3f-4bcd-aec0-1426812ae3ad)

:(

**Comment by swordcube** [comment]
> > > > just steal the actions from codename 🧌
> > > 
> > > 
> > > I FUCKING MIGHT
> > 
> > 
> > lmao
> 
> ![image](https://private-user-images.githubusercontent.com/12458328/368306131-68a24b2d-dc3f-4bcd-aec0-1426812ae3ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MDAzMDEsIm5iZiI6MTcyNjYwMDAwMSwicGF0aCI6Ii8xMjQ1ODMyOC8zNjgzMDYxMzEtNjhhMjRiMmQtZGMzZi00YmNkLWFlYzAtMTQyNjgxMmFlM2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE5MDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTNiOTE4NDU0NjdmNDVhZmYzNjg0MzczMmRkM2Q0MTY0Y2JkYzE4MTg2YWVlODJiMzljNTUxNWEwOWYzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tyssjg3wUQLWas1RCm3bBRaJkdiP2MFcNQW4_bOja6I)
> 
> :(

the only guess i have is it might be using a fucked up install of lime
if we figure out how to clear that shit out then it might just work again

**Comment by nebulazorua** [comment]
> > > > > just steal the actions from codename 🧌
> > > > 
> > > > 
> > > > I FUCKING MIGHT
> > > 
> > > 
> > > lmao
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/12458328/368306131-68a24b2d-dc3f-4bcd-aec0-1426812ae3ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MDAzMDEsIm5iZiI6MTcyNjYwMDAwMSwicGF0aCI6Ii8xMjQ1ODMyOC8zNjgzMDYxMzEtNjhhMjRiMmQtZGMzZi00YmNkLWFlYzAtMTQyNjgxMmFlM2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE5MDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTNiOTE4NDU0NjdmNDVhZmYzNjg0MzczMmRkM2Q0MTY0Y2JkYzE4MTg2YWVlODJiMzljNTUxNWEwOWYzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tyssjg3wUQLWas1RCm3bBRaJkdiP2MFcNQW4_bOja6I)
> > :(
> 
> the only guess i have is it might be using a fucked up install of lime if we figure out how to clear that shit out then it might just work again

its cus haxe versions, lime <8.1.2 breaks on haxe >4.3.4
welcome to the Haxe Ecosystem!

**Comment by nebulazorua** [comment]
I THINK I FIXED IT ITS COMPILING

**Comment by nebulazorua** [comment]
> I THINK I FIXED IT ITS COMPILING

nvm linux breaks when compiling lua
@crowplexus wanna work w/ rico to get it working on linux lol

**Comment by nebulazorua** [comment]
actions i BELIEVE work now
Might look into superpowers' fork to see how to fix linc_luajit for linux and mac

At some point I'd like to make my own custom bindings for lua and I wanna make a new lua API for troll (which'd prob be specified by using .tlua format, prob base it on smth like ITG or Andromeda)

**Comment by crowplexus** [comment]
> > I THINK I FIXED IT ITS COMPILING
> 
> nvm linux breaks when compiling lua @crowplexus wanna work w/ rico to get it working on linux lol

I'll give it a go and try fixing then LOL

**Comment by nebulazorua** [comment]
actions are fixed
thanks @moxie-coder for doing linux and mac shit

**Comment by moxie-coder** [comment]
> actions are fixed thanks @moxie-coder for doing linux and mac shit

np buddy
