### ISSUE TITLE
monster holds the strum note animations for an abnormal amount of time

### ISSUE THREAD

**Issue by riconuts** [riconuts/FNF-Troll-Engine#49]
### Describe your bug here.

https://github.com/user-attachments/assets/e50a5eb1-203b-49bb-8001-9004b415931c

probably not a monster specific issue might be bpm changes or fucked holds but i dunno lol that's why im writting this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no!

**Comment by nebulazorua** [comment]
I noticed this too, its to do w/ low BPM if I had to guess

It's likely related to shit i did recently to do w/ hold inputs no longer stopping if theres no tails left

**Comment by nebulazorua** [comment]
ok it seems related to holds that are really short likely combined w/ bpm change stuff
