### ISSUE TITLE
Compilation error / setHSBIntArray function

### ISSUE THREAD

**Issue by Rice1367** [riconuts/FNF-Troll-Engine#56]
### Describe your problem here.

```
source/funkin/states/options/NotesSubState.hx:288: characters 25-39 : funkin.objects.shaders.ColorSwap has no field setHSBIntArray
source/funkin/states/options/NotesSubState.hx:93: characters 14-28 : funkin.objects.shaders.ColorSwap has no field setHSBIntArray
C:/HaxeToolkit/haxe/lib/moonchart/git/src/moonchart/parsers/_internal/BitmapFile.hx:23: characters 15-19 : Cannot access data in static function
C:/HaxeToolkit/haxe/lib/moonchart/git/src/moonchart/parsers/_internal/BitmapFile.hx:24: characters 16-20 : Cannot access data in static function
```
It appears that in the NoteSubState there is a reference to a function called **setHSBIntArray** of the ColorSwap class that is not defined anywhere. I re-downloaded the engine to verify that I didn't miss anything, but there was no change, and I can't even find the function in the githug
Also, there seems to be some problems with Moonchart when compiling
Sorry for the inconvenience

### Are you modding a build from source or with scripts?

Scripts

### What is your build target?

Windows x64

**Comment by riconuts** [comment]
pushed the missing functions for colorswap, the moonchart stuff is a moonchart issue so lol

**Comment by Rice1367** [comment]
lol
thanks
sorry for asking about the Moonchart thing, I thought you might be able to help too, but I'll see what I can do. Thanks anyway
