### ISSUE TITLE
moonchart buggy

### ISSUE THREAD

**Issue by kangeluwu** [riconuts/FNF-Troll-Engine#57]
### Describe your bug here.

moonchart bugs and i don't know how to fix

### Command Prompt/Terminal logs (if existing)

```bash
source/funkin/data/Song.hx:147: characters 6-76 : error: Dynamic should be { }
source/funkin/data/Song.hx:147: characters 6-76 : ... have: moonchart.formats.BasicFormat<Dynamic, ...>
source/funkin/data/Song.hx:147: characters 6-76 : ... want: moonchart.formats.BasicFormat<{ }, ...>
source/funkin/data/Song.hx:501: characters 9-60 : error: Dynamic should be { }
source/funkin/data/Song.hx:501: characters 9-60 : ... have: moonchart.formats.DynamicFormat<>
source/funkin/data/Song.hx:501: characters 9-60 : ... want: moonchart.formats.BasicFormat<{ }, ...>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i replace moonchart.formats.BasicFormat<{}, {}>; to moonchart.formats.BasicFormat<Dynamic, Dynamic>;before and then into freeplay crashes so i change it back

**Comment by riconuts** [comment]
use moonchart 0.4.0, or just cast those values

**Comment by kangeluwu** [comment]
> use moonchart 0.4.0, or just cast those values

got fixed ty uwu
