### ISSUE TITLE
"Invalid commandline class : funkin.events.BaseEvent should be funkin.modchart.events.BaseEvent"

### ISSUE THREAD

**Issue by gratchtheechidna** [riconuts/FNF-Troll-Engine#59]
### Describe your problem here.

i got this problem after downloading the last commit, it happens when i use lime test windows, what should i do?

### Are you modding a build from source or with scripts?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by riconuts** [comment]
It works for me, are you sure you didn't change anything? Maybe by accident? Is that the only error or what else does it say before it?

**Comment by gratchtheechidna** [comment]
> It works for me, are you sure you didn't change anything? Maybe by accident? Is that the only error or what else does it say before it?

the only changes i made were very little sprite changes on the title state and freeplay state, and i was doing everything else thru the content folder. it's the only error that pops up when i compile.

**Comment by riconuts** [comment]
check if the 'source/funkin/events' folder exists if it does then get rid of it, 
I've only seen this type of error showing up when the package defined at the top of an hx file doesn't match the folder path it's in

**Comment by gratchtheechidna** [comment]
> check if the 'source/funkin/events' folder exists if it does then get rid of it, I've only seen this type of error showing up when the package defined at the top of an hx file doesn't match the folder path it's in

oh yeah, that was the problem, thank you for the help!
